/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package chargingstationapp;

import java.util.List;

/**
 *
 * @author afoud
 */
public class GUI extends javax.swing.JFrame {
    
    // Declaring the needed classes and nodes
    
    private SLList theList;
    private BinaryTree theBTree;
    private PriorityQueue theQueue;
    
    private ElectricVehicle newEV;
    private HybridVehicle newHV;
    
    private BTNode d01 = new BTNode("D01");
    private BTNode d02 = new BTNode("D02");
    private BTNode d03 = new BTNode("D03");
    private BTNode d04 = new BTNode("D04");
    private BTNode d05 = new BTNode("D05");
    private BTNode d06 = new BTNode("D06");
    private BTNode d06w = new BTNode("D06w");
    private BTNode d07 = new BTNode("D07");
    private BTNode d08 = new BTNode("D08");
    private BTNode d09 = new BTNode("D09");
    private BTNode d10 = new BTNode("D10");
    private BTNode d11 = new BTNode("D11");
    private BTNode d12 = new BTNode("D12");
    private BTNode d13 = new BTNode("D13");
    private BTNode d14 = new BTNode("D14");
    private BTNode d15 = new BTNode("D15");
    private BTNode d16 = new BTNode("D16");
    private BTNode d17 = new BTNode("D17");
    private BTNode d18 = new BTNode("D18");
    private BTNode d20 = new BTNode("D20");
    private BTNode d22 = new BTNode("D22");
    private BTNode d24 = new BTNode("D24");
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUI.class.getName());

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        
        // Instantiating the ADTs
        this.theList = new SLList();
        this.theBTree = new BinaryTree();
        this.theQueue = new PriorityQueue();
        
        // Adding the area codes at program start
        this.theBTree.insertNode(null, d01);
        this.theBTree.insertNode(d01, d02);
        this.theBTree.insertNode(d01, d03);
        this.theBTree.insertNode(d01, d04);
        this.theBTree.insertNode(d01, d05);
        this.theBTree.insertNode(d01, d06);
        this.theBTree.insertNode(d01, d06w);
        this.theBTree.insertNode(d01, d07);
        this.theBTree.insertNode(d01, d08);
        this.theBTree.insertNode(d01, d09);
        this.theBTree.insertNode(d01, d10);
        this.theBTree.insertNode(d01, d11);
        this.theBTree.insertNode(d01, d12);
        this.theBTree.insertNode(d01, d13);
        this.theBTree.insertNode(d01, d14);
        this.theBTree.insertNode(d01, d15);
        this.theBTree.insertNode(d01, d16);
        this.theBTree.insertNode(d01, d17);
        this.theBTree.insertNode(d01, d18);
        this.theBTree.insertNode(d01, d20);
        this.theBTree.insertNode(d01, d22);
        this.theBTree.insertNode(d01, d24);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        location_comboBox = new javax.swing.JComboBox<>();
        station_txtField = new javax.swing.JTextField();
        add_bttn = new javax.swing.JButton();
        search_bttn = new javax.swing.JButton();
        name_txtField = new javax.swing.JTextField();
        battery_txtField = new javax.swing.JTextField();
        vehicleType_txtField = new javax.swing.JTextField();
        join_bttn = new javax.swing.JButton();
        view_bttn = new javax.swing.JButton();
        deleteFirst_bttn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        outPuts_txtArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        location_comboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "D01", "D02", "D03", "D04", "D05", "D06", "D0W", "D07", "D08", "D09", "D10", "D11", "D12", "D13", "D14", "D15", "D16", "D17", "D18", "D20", "D22", "D24" }));

        add_bttn.setText("Add");
        add_bttn.addActionListener(this::add_bttnActionPerformed);

        search_bttn.setText("Search");
        search_bttn.addActionListener(this::search_bttnActionPerformed);

        join_bttn.setText("Join");
        join_bttn.addActionListener(this::join_bttnActionPerformed);

        view_bttn.setText("View");
        view_bttn.addActionListener(this::view_bttnActionPerformed);

        deleteFirst_bttn.setText("Remove first in Queue");
        deleteFirst_bttn.addActionListener(this::deleteFirst_bttnActionPerformed);

        outPuts_txtArea.setColumns(20);
        outPuts_txtArea.setRows(5);
        jScrollPane1.setViewportView(outPuts_txtArea);

        jLabel1.setText("Name");

        jLabel2.setText("Battery %");

        jLabel3.setText("EV or HV");

        jLabel4.setText("Add or Search for a station");

        jLabel5.setText("Join or View Priority Queue");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(add_bttn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(station_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(location_comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(search_bttn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(vehicleType_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(battery_txtField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(name_txtField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addComponent(jLabel5)))
                .addGap(37, 37, 37))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(deleteFirst_bttn)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(join_bttn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(view_bttn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(60, 60, 60))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(location_comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(station_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(battery_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_bttn)
                    .addComponent(search_bttn)
                    .addComponent(vehicleType_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(join_bttn)
                    .addComponent(view_bttn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteFirst_bttn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Clear all the input boxes
    private void clear() {
        station_txtField.setText("");
        name_txtField.setText("");
        battery_txtField.setText("");
        vehicleType_txtField.setText("");
    }
    
    /*
        Check if Station is already in system with the SLL
        If it is not added, add to the SLL and Binary Tree
    */
    private void add_bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_bttnActionPerformed
        // Enforcing correct input type
        try {       
            int newStationElement = Integer.parseInt(station_txtField.getText());

            // Check if the station is already added to the system
            if(!this.theList.searchKey(newStationElement)) {
                // If it is not then add it to the SLL and the correct BinaryTree Node
                this.theList.add(newStationElement);

                String location = (String)location_comboBox.getSelectedItem();
                this.theBTree.setStations(d01, location, newStationElement);
                this.outPuts_txtArea.append(" \n Station " + newStationElement + " has been added to " + location);
            }
            else {
                this.outPuts_txtArea.append(" \n This Station has already been added");
            }
        }
        catch (NumberFormatException e) {
            outPuts_txtArea.append("\n Please make sure to only input a valid station id. Example: 3");
        }
        clear();
    }//GEN-LAST:event_add_bttnActionPerformed

    /*
        Search for all the Stations in a spesific location
    */
    private void search_bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_bttnActionPerformed
        BTNode resultNode = theBTree.search((String)location_comboBox.getSelectedItem(), d01);
        
        // Gather all the result in the resultList variable
        List<Integer> resultList = resultNode.getStation();
        
        // Display the results if the size is greater or equal to 1
        if(resultList.size() >= 1) {
            outPuts_txtArea.append("\n The Stations in " + (String)location_comboBox.getSelectedItem() + " are: ");
            for(Integer i : resultList) {
                outPuts_txtArea.append(Integer.toString(i) + " ");
            }
        }
        else {
            outPuts_txtArea.append("\n There are no Stations in this location");
        }
        
    }//GEN-LAST:event_search_bttnActionPerformed
    
    // Join the priority queue
    private void join_bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_join_bttnActionPerformed
        // Get the correct Vehicle Type and store it into the variable newVehicle which is type Vehicle ( the parent class )
        try {
            Vehicle newVehicle = electricOrHybrid(vehicleType_txtField.getText());
            theQueue.enqueue(newVehicle.getPriority(), newVehicle);
        
            outPuts_txtArea.append("\n Vehicle has been added to the queue");
        }
        catch (Exception e) {
            outPuts_txtArea.append("\n Please make sure to correctly input the info. Example: Name = Antoine, Battery = 30, Vehicle Type = EV");
        }
        clear();
    }//GEN-LAST:event_join_bttnActionPerformed

    // View who is currently in the queue and their priority
    private void view_bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_bttnActionPerformed
        if(theQueue.size() == 0) {
            outPuts_txtArea.append("\n The Queue is Empty");
        }
        else {
            outPuts_txtArea.append("\n" + theQueue.printPQueue());
        }
    }//GEN-LAST:event_view_bttnActionPerformed

    // Remove the first Vehicle in the queue
    private void deleteFirst_bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteFirst_bttnActionPerformed
        theQueue.dequeue();
        outPuts_txtArea.append("\n The vehicle has been removed");
    }//GEN-LAST:event_deleteFirst_bttnActionPerformed
    
    // Implement the correct Vehicle Child class to get the correct priority
    private Vehicle electricOrHybrid(String type) {
        if("EV".equals(type)) {
            newEV = new ElectricVehicle(name_txtField.getText(), Integer.parseInt(battery_txtField.getText()));
            return newEV;
        }
        else if("HV".equals(type)) {
            newHV = new HybridVehicle(name_txtField.getText(), Integer.parseInt(battery_txtField.getText()));
            return newHV;
        }
        else {
            outPuts_txtArea.append("\n Incorrect Vehicle type");
            return null;
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_bttn;
    private javax.swing.JTextField battery_txtField;
    private javax.swing.JButton deleteFirst_bttn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton join_bttn;
    private javax.swing.JComboBox<String> location_comboBox;
    private javax.swing.JTextField name_txtField;
    private javax.swing.JTextArea outPuts_txtArea;
    private javax.swing.JButton search_bttn;
    private javax.swing.JTextField station_txtField;
    private javax.swing.JTextField vehicleType_txtField;
    private javax.swing.JButton view_bttn;
    // End of variables declaration//GEN-END:variables
}
